export const DESTAQUES = 'DESTAQUES',
    GENEROS1 = 'GENEROS1',
    GENEROS2 = 'GENEROS2',
    GENEROS3 = 'GENEROS3',
    BUSCAR_CURTA = 'BUSCAR_CURTA',
    LIMPAR_CURTA = 'LIMPAR_CURTA',
    LIMPAR_DESTAQUES = 'LIMPAR_DESTAQUES',
    LIMPAR_GENEROS = 'LIMPAR_GENEROS';